---
- name: Throwaway setup
  hosts: all
  become: yes
  roles:
    - {role: base.debian, when: ansible_os_family == 'Debian' }
    - {role: base.archlinux, when: ansible_os_family == 'Archlinux' }
    - flatpak
    - openvpn
    - iptables
