---
- name: Copy OpenVPN files
  ansible.builtin.copy:
    src: /vagrant/guest_volume/etc/openvpn/client/
    dest: /etc/openvpn/client/
    force: yes

- name: Copy config shuffle script
  ansible.builtin.copy:
    src: /vagrant/guest_volume/usr/bin/openvpn-config-shuffle.sh
    dest: /usr/bin
    force: yes
    mode: 0755

- name: Copy config shuffle systemd service config
  ansible.builtin.copy:
    src: /vagrant/guest_volume/etc/systemd/system/openvpn-config-shuffle.service
    dest: /etc/systemd/system/
    force: yes
    mode: 0644

- name: Enable openvpn-config-shuffle.service
  systemd:
    name: openvpn-config-shuffle.service
    enabled: yes
    daemon_reload: yes
    masked: no

- name: Start openvpn-config-shuffle.service
  systemd:
    name: openvpn-config-shuffle.service
    state: started

- name: Enable openvpn-client@client.service
  systemd:
    name: openvpn-client@client.service
    enabled: yes
    daemon_reload: yes
    masked: no

- name: Start openvpn-client@client.service
  systemd:
    name: openvpn-client@client.service
    state: started
